version: '3.7'
services:
  mywebapi:
    image: nelson9199/my-web-api
    build: .
    ports:
      - '8080:80'
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'Pa55w0rd2019'
      MSSQL_PID: Express
    container_name: db
    ports:
      - '1433:1433'
